### ISSUE TITLE
Is there any way to resize container view? inside cell?

### ISSUE THREAD

**Issue by thihaaung6245** [varunpm1/VPAccordionAnimation#1]
First of all, thanks for offering which I am looking for, UIViewController inside UITableViewCell.
Thank you.

At your example, it only show the full screen of container view.But the cell is still tappable, I can't tap lower cell. A little help? 

Also, more detail customization documentation is appreciated.

**Comment by varunpm1** [comment]
Hi,

Yes it can be handled if you could override the `heightForRowAtIndexPath` in your view controller and return the required height (you can make use of `isIndexPathExpanded(indexPath)` to check if expanded or collapsed.).

Yeah sure, I'll add more detailed documentation whenever possible.

Thanks.
